Modify entities to conform to strict rules
wafflestudio/snuboard-server pull request #10
Opened 2021-02-12 17:00 UTC by gyusang

컴파일 에러가 나지 않도록 변수 선언과 함수 로직을 일부 수정했습니다.
This PR may resolve #9

2021-02-12 17:44 UTC, eldpswp99 requested changes
entity파일만이 수정되어 있는 상황이어서 프로젝트 루트에 tsconfig의 strict:true를 추가하였더니 빌드 시에 에러가 발생했습니다. 서버가 빌드되도록 전체적인 코드의 에러나는 부분을 수정하여 커밋하였습니다. 기존의 코드와는 findOneIfRefreshTokenMatches에서 null을 리턴하는지, undefined를 리턴하는가가 다르고, 나머지는 동일합니다!

2021-02-12 18:50 UTC, gyusang commented
`package.json`은 변화가 없는데 `package-lock.json`에는 변화가 있는 이유가 무엇인가요?

2021-02-13 03:37 UTC, eldpswp99 commented
https://stackoverflow.com/questions/63742539/npm-install-changes-my-package-lock-json-will-that-interfere-with-the-remote-co

찾아보니 저와 상규님의 컴퓨터 상황이 달라서 package-lock.json이 달라지는 것 같습니다. 상규님이올려주신 커밋의 package-lock.json은 version2이고 제 기존 것에서는 version 1으로 나오게 됩니다. 저 링크에서 언급되었던 것처럼 npm이 npm ci를 통해 설치하면 package-lock.json을 기반으로 설치하지만, npm install을 기반으로 설치하면 package.json을 기반으로 설치하고, pakcage-lock.json을 새로 작성하게 됩니다. 제 컴퓨터에서는 npm install을 다시 하면 version1으로 돌아가네요. 아마 그러한 이유일 듯 합니다. 정확히 어떤 부분이 달라서 버전이 달라지는지는 모르겠지만, 일단 이유는 환경의 차이가 맞는듯 합니다.

이 PR은 제가 컴파일을 수정하는데 있어서 !을 너무 남발한듯 하여.. 좀 더 코드를 이쁘게 수정하고 커밋하도록 하겠습니다

2021-02-13 16:03 UTC, gyusang reviewed
네, 좋습니다!

2021-02-13 16:04 UTC, eldpswp99 approved these changes

2021-02-13 16:04 UTC, merged