notice-api
wafflestudio/snuboard-server pull request #20
Opened 2021-02-16 15:20 UTC by min112402

resolves [#7](https://github.com/wafflestudio/snuboard-server/issues/7)

#14와 [is_scrapped추가](https://wafflestudio.slack.com/archives/C01KPDNC490/p1613224771200800) 를 반영해서 notice-api 를 구현했습니다.

department에서처럼 constants와 init으로 초기 값을 설정합니다.

QueryBuilder가 상당히 복잡하게 연결되어있습니다. 나름 정리를 했지만 좀 더 정리를 해야할 것 같습니다.!

2021-02-17 08:48 UTC, eldpswp99 requested changes
Init과정에서 department id를 기반으로 Init이 작동하는데, 이 방법은 저와 상민님의 db가 정확히 동일해야 동작하지만, 제 로컬의 db와 상민님의 db가 달라 문제가 발생하였습니다. 그래서 현재 제가 pull 받아서 구동했을 때에는 정상적으로 동작하지 않네요. 그래서 전체적으로 리뷰를 하는 것은 현 시점에서 무리라고 생각돼서, 이 부분을 수정해주시면 리뷰를 마저 하도록 하겠습니다. 고생 많으셨습니다. :)

2021-02-17 09:55 UTC, min112402 commented
리뷰 감사합니다.!   ' 작동은 되는' 수준의 코드여서  PR보내는 건 조금 일렀던 것 같습니다.  

init 은 빨리 고쳐서 올려보겠습니다.

테스트에 시간을 많이 쓰다보니 테스트코드를 만든 다음에 코드를 고칠 생각으로 복붙한 부분이 좀 있습니다. 더 완성도를 높여서 PR 보내겠습니다.

2021-02-17 11:03 UTC, eldpswp99 commented
> 리뷰 감사합니다.! ' 작동은 되는' 수준의 코드여서 PR보내는 건 조금 일렀던 것 같습니다.
> 
> init 은 빨리 고쳐서 올려보겠습니다.
> 
> 테스트에 시간을 많이 쓰다보니 테스트코드를 만든 다음에 코드를 고칠 생각으로 복붙한 부분이 좀 있습니다. 더 완성도를 높여서 PR 보내겠습니다.

네넵 PR 열어 두시고 커밋하셔도 갱신 그대로 돼서 열어두셔도 괜찮을 것 같습니다!

2021-02-17 14:00 UTC, gyusang commented
cursor는 어떻게 initialize해야 하나요?

2021-02-17 14:01 UTC, gyusang commented
> cursor는 어떻게 initialize해야 하나요?

https://github.com/wafflestudio/snuboard-server/blob/359b7decf6fb970576e4ed001c6d79676ddca688/src/notice/notice.init.ts#L24-L27

참고해서 만들어보겠습니다.

2021-02-17 14:04 UTC, gyusang commented
NoticeTag에 CASCADE가 적용되지 않은 이유가 있을까요?

2021-02-17 14:45 UTC, min112402 commented
> NoticeTag에 CASCADE가 적용되지 않은 이유가 있을까요?

제가 확인을 못했네요.. 찾아주셔서 감사합니다 

수정해놓겠습니다.

2021-02-18 14:21 UTC, min112402 commented on src/notice/dto/searchFollowedNotice.dto.ts
> +  keywords!: string;
keyword도 여러개의 단어가 입력으로 들어올 수 있어서 tags처럼 keywords로 변경하려 합니다.

2021-02-18 17:27 UTC, eldpswp99 requested changes
코드가 가독성이나 재사용 면에서 저번 PR보다 훨씬 좋아진 것 같습니다! 좋네요 ㅎㅎ query가 되게 복잡한 endpoint들인데, querybuilder를 적절히 함수화해서 활용하셔서 find를 때마다 사용하는 것보다 더 아름답게 구현된 듯 합니다.

제가 리뷰한 부분 봐주시고, 다른 의견이 있으시거나 어떤 말이든 하실 말씀이 있으시다면 답으로 남겨주세요!  추가적으로 제가 리뷰에 몇 가지를 적었지만 그것들 이외에도 변수가 any로 선언되어 있는 것들이 꽤 있는 것 같습니다, 타입 스크립트의 장점을 최대한 활용하기 위해서 이러한 부분을 최대한 없애주시면 좋을 것 같아요, 정말 수고 많으셨습니다!

2021-02-18 17:27 UTC, eldpswp99 commented on src/notice/notice.service.ts
> +    return response;
notice의 모든 endpoint가 authorization을 요구하고, scrap여부가 항상 포함되는 것처럼 보여서,(후에 추가되는 endpoint도 포함할 것 같구요) makeResponse안에 attachIsScrapped를 넣는 것도 좋아보입니다!

2021-02-18 17:27 UTC, eldpswp99 commented on src/notice/notice.service.ts
> +    const user = await User.findOne(req.user);
const user : User | undefined 로 해주셔서 타입 체킹 해주세요 :)

2021-02-18 17:27 UTC, eldpswp99 commented on src/notice/notice.service.ts
> +    const user = await User.findOne(req.user);
이쪽도...!

2021-02-19 01:36 UTC, min112402 commented on src/notice/notice.init.ts
> +          NoticeTag.save(NoticeTag.create({ notice: notice, tag: tag }));
네넵

2021-02-19 03:28 UTC, min112402 commented on src/notice/notice.service.ts
> +
tagQb는 where절이 너무 길어지는 걸 막기위해 string을 대신해서 넣은 querybuilder입니다. 그래서 tagQb에서 바로 getMany()를 하는 경우는 고려하지 않고 만들었습니다...

에러 메시지의 경우에는 지금 tagQb에는 setParameter('tags', tags)를 해주지 않았기 때문에 sql 쿼리에 'tags'라는 parameter이름이 그대로 들어가서 오류가 나는 것 같습니다.  

+   setParameter를 해줘도 오류는 안나지만 getMany()를 했을 때 아무것도 안나옵니다... 이건 쿼리를 좀 살펴봐야 원인을 알 것 같네요

2021-02-19 03:32 UTC, min112402 commented on src/notice/notice.service.ts
> +    return response;
넵넵 user IsScrapped에서만 user 정보가 필요한  경우(/id,/department)가 있어서 user와 관련된 로직을 분리했었습니다.(+IsScrapped가 나중에 추가되기도 했고요) 
makeResponse 안에 넣는 것도 좋을 것 같습니다!

2021-02-19 09:40 UTC, min112402 commented
<notice-api 리팩토링>
- init함수들을 하나로 묶어서 정리했습니다.
- attachIsScrapped가 makeResponse에 포함되게 했습니다.
- validateQuery에서 user, department 검증도 한번에 하게 바꿨습니다. 
- service의 search 함수들도 중복이라고 생각해서 getNotice/getFollowedNotice에서 query의 타입에 따라 처리하게 했습니다.

2021-02-19 11:34 UTC, eldpswp99 approved these changes
너무 좋네요! 고생 많으셨습니다 '-')=b

2021-02-19 11:34 UTC, merged