get departments query improved
wafflestudio/snuboard-server pull request #56
Opened 2021-05-13 04:52 UTC by eldpswp99

get departments의 쿼리에서 

department하나당 쿼리 한개를 추가적으로 호출하는 N+1가 발생해서 이 부분의 쿼리를 수정하였습니다

2021-05-13 18:37 UTC, gyusang requested changes
migration generate해서 commit해주실 수 있나요? DB 상태때문에 어려우면 제가 하겠습니다

2021-05-13 18:41 UTC, eldpswp99 commented
> migration generate해서 commit해주실 수 있나요? DB 상태때문에 어려우면 제가 하겠습니다

어떤 migration을 말씀하시는지 알 수 있을까요?

tag name의 경우는  name을 이용해서 찾았을 때 row가 그리 많지 않아 쿼리문의 속도가 빨라 추가하지 않았었습니다. 추가하는게 나으려나요?

2021-05-13 18:43 UTC, gyusang commented
지금 태그 디비구조가 변경된 거 아닌가요?

2021-05-13 18:46 UTC, eldpswp99 commented
> 지금 태그 디비구조가 변경된 거 아닌가요?
> 엔티티가 수정되어서 변경된 줄 알았습니다

아 저 부분은 column이 아니라 Notice의 response data에 달아놓는 것이었는데, 기존에 string배열로 하니까 뭔가 직관적이지 않아서 Tag를 가지도록 바꾼 것이었습니다. db테이블의 변화는 없습니다.

2021-05-13 19:19 UTC, gyusang approved these changes
아하 그랬군요

2021-05-14 04:19 UTC, min112402 approved these changes
좋습니당

2021-05-14 04:19 UTC, min112402 commented on src/notice/notice.service.ts
> +      .innerJoin(
좋습니당
속도는 크게 차이가 없군요...

2021-05-14 04:24 UTC, merged